<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Yoobee Calculator</title>

    <link rel="stylesheet" href="../node_modules/bulma/css/bulma.css">
    <style>
        .inner {
            padding: 20px 10px;
        }

        .form {
            display: none;
        }

        .circle,
        .square,
        .rectangle {
            background-color: blue;
            border: 4px solid black;
        }

        .circle,
        .square {
            width: 200px;
            height: 200px;
            display: block;
        }

        .circle {
            border-radius: 50%;
        }

        .rectangle {
            width: 350px;
            height: 200px;
        }

        .tall {
            width: 200px;
            height: 350px;
        }
    </style>
</head>
<body>
    <div class="container inner">
        <div class="content">
            <h1>Yoobee Calculator</h1>
            <div>
                <?php include("displayDate.php"); ?>
                <p>Please choose the shape for which you want to calculate the properties</p>
            </div>
        </div>
        <div class="tabs is-boxed">
            <ul>
                <li id="showCircleForm" class="form-selector is-active" data-form="circleForm">
                    <a>
                        <span>Circle</span>
                    </a>
                </li>
                <li id="showSquareForm" class="form-selector" data-form="squareForm">
                    <a>
                        <span>Square</span>
                    </a>
                </li>
                <li id="showRectangleForm" class="form-selector" data-form="rectangleForm">
                    <a>
                        <span>Rectangle</span>
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <form id="circleForm" class="form" action="calc.phtml" method="POST">
                <div class="field">
                    <label class="label">Enter Radius</label>
                    <div class="control">
                        <input class="input" name="radius" type="text" placeholder="Radius">
                    </div>
                </div>
                <input type="hidden" name="action" value="circle">
                <input type="submit" class="button is-success">
            </form>

            <form id="squareForm" class="form" action="calc.phtml" method="POST">
                <div class="field">
                    <label class="label">Enter Side Length</label>
                    <div class="control">
                        <input class="input" name="side" type="text" placeholder="Side Length">
                    </div>
                </div>
                <input type="hidden" name="action" value="square">
                <input type="submit" class="button is-success">
            </form>

            <form id="rectangleForm" class="form" action="calc.phtml" method="POST">
                <div class="field">
                    <label class="label">Enter Width</label>
                    <div class="control">
                        <input class="input" name="width" type="text" placeholder="Width">
                    </div>
                    <br>
                    <label class="label">Enter Height</label>
                    <div class="control">
                        <input class="input" name="height" type="text" placeholder="Height">
                    </div>
                </div>
                <input type="hidden" name="action" value="rectangle">
                <input type="submit" class="button is-success">
            </form>
            <div>
                <?php include("calculate.php"); ?>
            </div>
        </div>
    </div>
    <script src="../node_modules/jquery/dist/jquery.min.js"></script>
    <script src="./calc.js"></script>
</body>
</html>